name: retrocode.io to cloud.tencent
on:
  push:
    branches:
      - main
jobs:
  build:
    # 运行环境:ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: 获取项目源码
        uses: actions/checkout@main
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: 校验源码目录
        run: |
          ls -l /home/runner/work/retrocode.io/retrocode.io
      - name: 导出源码至轻量云
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          # 直接部署整个项目
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          AFTER_COMMAND: ${{ secrets.DEPLOY_AFTER_COMMAND }}
